# Generated by Django 2.2.12 on 2021-06-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_file', models.FileField(upload_to='')),
                ('movie_photo', models.FileField(upload_to='')),
                ('movie_description', models.TextField(max_length=10000)),
                ('movie_rate', models.IntegerField(default=0)),
                ('movie_year', models.IntegerField(default=0)),
                ('date_uploaded', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugamix.Category')),
            ],
        ),
    ]
